import 'package:flutter/material.dart';
import 'package:raqami/l10n/app_localizations.dart';
import 'package:raqami/src/presentation/ui/theme/raqami_theme.dart';
import 'package:raqami/src/presentation/ui/theme/raqami_theme_data.dart';
import 'package:raqami/src/presentation/ui/typography/raqami_text.dart';
import 'package:raqami/src/presentation/ui/typography/raqami_text_style.dart';

class PrivacyPolicyScreen extends StatelessWidget {
  const PrivacyPolicyScreen({super.key});

  String _getSectionTitle(String enTitle, String arTitle, String locale) {
    return locale == 'ar' ? arTitle : enTitle;
  }

  String _getSectionContent(String enContent, String arContent, String locale) {
    return locale == 'ar' ? arContent : enContent;
  }

  @override
  Widget build(BuildContext context) {
    final theme = RaqamiTheme.of(context);
    final localizations = AppLocalizations.of(context)!;

    return Scaffold(
      backgroundColor: theme.colors.backgroundPrimary,
      appBar: AppBar(
        backgroundColor: theme.colors.backgroundPrimary,
        elevation: 0,
        leading: IconButton(
          icon: Icon(
            Icons.arrow_back,
            color: theme.colors.foregroundPrimary,
          ),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: RaqamiText(
          localizations.privacyPolicy,
          style: RaqamiTextStyles.heading3,
          textColor: theme.colors.foregroundPrimary,
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _buildSection(
              context,
              theme,
              _getSectionTitle(
                'Privacy Policy',
                'سياسة الخصوصية',
                localizations.localeName,
              ),
              _getSectionContent(
                'Last updated: January 04, 2026\n\n'
                'This Privacy Policy describes Our policies and procedures on the collection, '
                'use and disclosure of Your information when You use the Service and tells You '
                'about Your privacy rights and how the law protects You.\n\n'
                'We use Your Personal data to provide and improve the Service. By using the '
                'Service, You agree to the collection and use of information in accordance with '
                'this Privacy Policy.',
                'آخر تحديث: 04 يناير 2026\n\n'
                'تصف سياسة الخصوصية هذه سياساتنا وإجراءاتنا المتعلقة بجمع واستخدام وكشف معلوماتك '
                'عند استخدام الخدمة وتخبرك عن حقوق الخصوصية الخاصة بك وكيف يحميك القانون.\n\n'
                'نستخدم بياناتك الشخصية لتوفير وتحسين الخدمة. باستخدام الخدمة، فإنك توافق على جمع '
                'واستخدام المعلومات وفقًا لسياسة الخصوصية هذه.',
                localizations.localeName,
              ),
            ),
            const SizedBox(height: 32),
            _buildSection(
              context,
              theme,
              _getSectionTitle(
                'Interpretation and Definitions',
                'التفسير والتعريفات',
                localizations.localeName,
              ),
              _getSectionContent(
                'Interpretation\n\n'
                'The words whose initial letters are capitalized have meanings defined under '
                'the following conditions. The following definitions shall have the same '
                'meaning regardless of whether they appear in singular or in plural.\n\n'
                'Definitions\n\n'
                'For the purposes of this Privacy Policy:\n\n'
                '• Account means a unique account created for You to access our Service or parts of our Service.\n\n'
                '• Application refers to Raqami, the software program provided by the Company.\n\n'
                '• Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Raqami.\n\n'
                '• Country refers to: United Arab Emirates\n\n'
                '• Device means any device that can access the Service such as a computer, a cell phone or a digital tablet.\n\n'
                '• Personal Data is any information that relates to an identified or identifiable individual.\n\n'
                '• Service refers to the Application.\n\n'
                '• Service Provider means any natural or legal person who processes the data on behalf of the Company.\n\n'
                '• Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.\n\n'
                '• You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.',
                'التفسير\n\n'
                'الكلمات التي تبدأ بأحرف كبيرة لها معاني محددة تحت الشروط التالية. التعريفات التالية '
                'سيكون لها نفس المعنى بغض النظر عما إذا كانت تظهر بصيغة المفرد أو الجمع.\n\n'
                'التعريفات\n\n'
                'لأغراض سياسة الخصوصية هذه:\n\n'
                '• الحساب يعني حسابًا فريدًا تم إنشاؤه لك للوصول إلى خدمتنا أو أجزاء من خدمتنا.\n\n'
                '• التطبيق يشير إلى Raqami، برنامج الكمبيوتر المقدم من الشركة.\n\n'
                '• الشركة (يشار إليها إما باسم "الشركة"، "نحن"، "لنا" أو "خاصتنا" في هذه الاتفاقية) تشير إلى Raqami.\n\n'
                '• البلد يشير إلى: الإمارات العربية المتحدة\n\n'
                '• الجهاز يعني أي جهاز يمكنه الوصول إلى الخدمة مثل الكمبيوتر أو الهاتف الخلوي أو الجهاز اللوحي الرقمي.\n\n'
                '• البيانات الشخصية هي أي معلومات تتعلق بفرد محدد أو يمكن تحديده.\n\n'
                '• الخدمة تشير إلى التطبيق.\n\n'
                '• مقدم الخدمة يعني أي شخص طبيعي أو قانوني يعالج البيانات نيابة عن الشركة.\n\n'
                '• بيانات الاستخدام تشير إلى البيانات التي يتم جمعها تلقائيًا، إما التي يتم إنشاؤها من خلال استخدام الخدمة أو من البنية التحتية للخدمة نفسها.\n\n'
                '• أنت يعني الفرد الذي يصل إلى الخدمة أو يستخدمها، أو الشركة، أو الكيان القانوني الآخر الذي يمثله هذا الفرد في الوصول إلى الخدمة أو استخدامها، حسب الاقتضاء.',
                localizations.localeName,
              ),
            ),
            const SizedBox(height: 32),
            _buildSection(
              context,
              theme,
              _getSectionTitle(
                'Collecting and Using Your Personal Data',
                'جمع واستخدام بياناتك الشخصية',
                localizations.localeName,
              ),
              _getSectionContent(
                'Types of Data Collected\n\n'
                'Personal Data\n\n'
                'While using Our Service, We may ask You to provide Us with certain personally '
                'identifiable information that can be used to contact or identify You. '
                'Personally identifiable information may include, but is not limited to:\n\n'
                '• Email address\n'
                '• First name and last name\n'
                '• Phone number\n'
                '• Usage Data\n\n'
                'Usage Data\n\n'
                'Usage Data is collected automatically when using the Service.\n\n'
                'Usage Data may include information such as Your Device\'s Internet Protocol address (e.g. IP address), '
                'browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, '
                'the time spent on those pages, unique device identifiers and other diagnostic data.\n\n'
                'When You access the Service by or through a mobile device, We may collect certain information automatically, '
                'including, but not limited to, the type of mobile device You use, Your mobile device\'s unique ID, '
                'the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, '
                'unique device identifiers and other diagnostic data.',
                'أنواع البيانات المجمعة\n\n'
                'البيانات الشخصية\n\n'
                'أثناء استخدام خدمتنا، قد نطلب منك تزويدنا بمعلومات تعريف شخصية معينة يمكن استخدامها للاتصال بك أو التعرف عليك. '
                'قد تشمل معلومات التعريف الشخصية، على سبيل المثال لا الحصر:\n\n'
                '• عنوان البريد الإلكتروني\n'
                '• الاسم الأول والاسم الأخير\n'
                '• رقم الهاتف\n'
                '• بيانات الاستخدام\n\n'
                'بيانات الاستخدام\n\n'
                'يتم جمع بيانات الاستخدام تلقائيًا عند استخدام الخدمة.\n\n'
                'قد تتضمن بيانات الاستخدام معلومات مثل عنوان بروتوكول الإنترنت لجهازك (مثل عنوان IP)، '
                'نوع المتصفح، إصدار المتصفح، صفحات خدمتنا التي تزورها، وقت وتاريخ زيارتك، '
                'الوقت الذي تقضيه على تلك الصفحات، معرفات الأجهزة الفريدة وبيانات التشخيص الأخرى.\n\n'
                'عند الوصول إلى الخدمة من خلال جهاز محمول أو عبره، قد نجمع معلومات معينة تلقائيًا، '
                'بما في ذلك، على سبيل المثال لا الحصر، نوع الجهاز المحمول الذي تستخدمه، المعرف الفريد لجهازك المحمول، '
                'عنوان IP لجهازك المحمول، نظام التشغيل المحمول الخاص بك، نوع متصفح الإنترنت المحمول الذي تستخدمه، '
                'معرفات الأجهزة الفريدة وبيانات التشخيص الأخرى.',
                localizations.localeName,
              ),
            ),
            const SizedBox(height: 32),
            _buildSection(
              context,
              theme,
              _getSectionTitle(
                'Use of Your Personal Data',
                'استخدام بياناتك الشخصية',
                localizations.localeName,
              ),
              _getSectionContent(
                'The Company may use Personal Data for the following purposes:\n\n'
                '• To provide and maintain our Service, including to monitor the usage of our Service.\n\n'
                '• To manage Your Account: to manage Your registration as a user of the Service.\n\n'
                '• For the performance of a contract: the development, compliance and undertaking of the purchase contract.\n\n'
                '• To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.\n\n'
                '• To provide You with news, special offers, and general information about other goods, services and events.\n\n'
                '• To manage Your requests: To attend and manage Your requests to Us.\n\n'
                '• For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.\n\n'
                '• For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service.',
                'قد تستخدم الشركة البيانات الشخصية للأغراض التالية:\n\n'
                '• لتوفير وصيانة خدمتنا، بما في ذلك مراقبة استخدام خدمتنا.\n\n'
                '• لإدارة حسابك: لإدارة تسجيلك كمستخدم للخدمة.\n\n'
                '• لأداء العقد: تطوير وامتثال وتنفيذ عقد الشراء.\n\n'
                '• للاتصال بك: للاتصال بك عبر البريد الإلكتروني أو المكالمات الهاتفية أو الرسائل النصية القصيرة أو غيرها من أشكال الاتصال الإلكتروني المكافئة.\n\n'
                '• لتزويدك بالأخبار والعروض الخاصة والمعلومات العامة حول السلع والخدمات والأحداث الأخرى.\n\n'
                '• لإدارة طلباتك: للرد على طلباتك وإدارتها.\n\n'
                '• للتحويلات التجارية: قد نستخدم معلوماتك لتقييم أو إجراء دمج أو تصفية أو إعادة هيكلة أو إعادة تنظيم أو حل أو بيع أو نقل آخر لبعض أو كل أصولنا.\n\n'
                '• لأغراض أخرى: قد نستخدم معلوماتك لأغراض أخرى، مثل تحليل البيانات، وتحديد اتجاهات الاستخدام، وتحديد فعالية حملاتنا الترويجية وتقييم وتحسين خدمتنا.',
                localizations.localeName,
              ),
            ),
            const SizedBox(height: 32),
            _buildSection(
              context,
              theme,
              _getSectionTitle(
                'Retention of Your Personal Data',
                'الاحتفاظ ببياناتك الشخصية',
                localizations.localeName,
              ),
              _getSectionContent(
                'The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. '
                'We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, '
                'and enforce our legal agreements and policies.\n\n'
                'The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, '
                'except when this data is used to strengthen the security or to improve the functionality of Our Service, '
                'or We are legally obligated to retain this data for longer periods.',
                'ستحتفظ الشركة ببياناتك الشخصية فقط طالما كان ذلك ضروريًا للأغراض المحددة في سياسة الخصوصية هذه. '
                'سنحتفظ ببياناتك الشخصية ونستخدمها بالقدر اللازم للامتثال لالتزاماتنا القانونية وحل النزاعات '
                'وتنفيذ اتفاقياتنا وسياساتنا القانونية.\n\n'
                'ستحتفظ الشركة أيضًا ببيانات الاستخدام لأغراض التحليل الداخلي. يتم الاحتفاظ ببيانات الاستخدام عمومًا لفترة أقصر من الوقت، '
                'إلا عندما تُستخدم هذه البيانات لتعزيز الأمان أو لتحسين وظائف خدمتنا، '
                'أو عندما نكون ملزمين قانونيًا بالاحتفاظ بهذه البيانات لفترات أطول.',
                localizations.localeName,
              ),
            ),
            const SizedBox(height: 32),
            _buildSection(
              context,
              theme,
              _getSectionTitle(
                'Transfer of Your Personal Data',
                'نقل بياناتك الشخصية',
                localizations.localeName,
              ),
              _getSectionContent(
                'Your information, including Personal Data, is processed at the Company\'s operating offices and in any other places '
                'where the parties involved in the processing are located. It means that this information may be transferred to — '
                'and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction '
                'where the data protection laws may differ from those from Your jurisdiction.\n\n'
                'Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.\n\n'
                'The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy.',
                'يتم معالجة معلوماتك، بما في ذلك البيانات الشخصية، في مكاتب تشغيل الشركة وفي أي أماكن أخرى '
                'حيث توجد الأطراف المشاركة في المعالجة. هذا يعني أن هذه المعلومات قد يتم نقلها إلى — '
                'والاحتفاظ بها على — أجهزة الكمبيوتر الموجودة خارج ولايتك أو مقاطعتك أو بلدك أو الولاية القضائية الحكومية الأخرى '
                'حيث قد تختلف قوانين حماية البيانات عن تلك الموجودة في ولايتك القضائية.\n\n'
                'موافقتك على سياسة الخصوصية هذه متبوعة بتقديمك لمثل هذه المعلومات تمثل موافقتك على هذا النقل.\n\n'
                'ستتخذ الشركة جميع الخطوات المعقولة اللازمة لضمان معالجة بياناتك بأمان ووفقًا لسياسة الخصوصية هذه.',
                localizations.localeName,
              ),
            ),
            const SizedBox(height: 32),
            _buildSection(
              context,
              theme,
              _getSectionTitle(
                'Delete Your Personal Data',
                'حذف بياناتك الشخصية',
                localizations.localeName,
              ),
              _getSectionContent(
                'You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.\n\n'
                'Our Service may give You the ability to delete certain information about You from within the Service.\n\n'
                'You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, '
                'and visiting the account settings section that allows you to manage Your personal information. '
                'You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.\n\n'
                'Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.',
                'لديك الحق في حذف أو طلب مساعدتنا في حذف البيانات الشخصية التي جمعناها عنك.\n\n'
                'قد تمنحك خدمتنا القدرة على حذف معلومات معينة عنك من داخل الخدمة.\n\n'
                'يمكنك تحديث أو تعديل أو حذف معلوماتك في أي وقت عن طريق تسجيل الدخول إلى حسابك، إذا كان لديك واحد، '
                'وزيارة قسم إعدادات الحساب الذي يسمح لك بإدارة معلوماتك الشخصية. '
                'يمكنك أيضًا الاتصال بنا لطلب الوصول إلى أو تصحيح أو حذف أي معلومات شخصية قدمتها لنا.\n\n'
                'يرجى ملاحظة، مع ذلك، أننا قد نحتاج إلى الاحتفاظ بمعلومات معينة عندما يكون لدينا التزام قانوني أو أساس قانوني للقيام بذلك.',
                localizations.localeName,
              ),
            ),
            const SizedBox(height: 32),
            _buildSection(
              context,
              theme,
              _getSectionTitle(
                'Disclosure of Your Personal Data',
                'الكشف عن بياناتك الشخصية',
                localizations.localeName,
              ),
              _getSectionContent(
                'Business Transactions\n\n'
                'If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. '
                'We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.\n\n'
                'Law enforcement\n\n'
                'Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law '
                'or in response to valid requests by public authorities (e.g. a court or a government agency).\n\n'
                'Other legal requirements\n\n'
                'The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:\n\n'
                '• Comply with a legal obligation\n'
                '• Protect and defend the rights or property of the Company\n'
                '• Prevent or investigate possible wrongdoing in connection with the Service\n'
                '• Protect the personal safety of Users of the Service or the public\n'
                '• Protect against legal liability',
                'المعاملات التجارية\n\n'
                'إذا كانت الشركة متورطة في دمج أو استحواذ أو بيع أصول، قد يتم نقل بياناتك الشخصية. '
                'سنقدم إشعارًا قبل نقل بياناتك الشخصية وخضوعها لسياسة خصوصية مختلفة.\n\n'
                'إنفاذ القانون\n\n'
                'تحت ظروف معينة، قد يُطلب من الشركة الكشف عن بياناتك الشخصية إذا كان ذلك مطلوبًا بموجب القانون '
                'أو استجابة لطلبات صالحة من السلطات العامة (مثل المحكمة أو وكالة حكومية).\n\n'
                'متطلبات قانونية أخرى\n\n'
                'قد تكشف الشركة عن بياناتك الشخصية بناءً على الاعتقاد بحسن النية أن مثل هذا الإجراء ضروري:\n\n'
                '• للامتثال لالتزام قانوني\n'
                '• لحماية والدفاع عن حقوق أو ممتلكات الشركة\n'
                '• لمنع أو التحقيق في أي مخالفة محتملة فيما يتعلق بالخدمة\n'
                '• لحماية السلامة الشخصية لمستخدمي الخدمة أو الجمهور\n'
                '• للحماية من المسؤولية القانونية',
                localizations.localeName,
              ),
            ),
            const SizedBox(height: 32),
            _buildSection(
              context,
              theme,
              _getSectionTitle(
                'Security of Your Personal Data',
                'أمان بياناتك الشخصية',
                localizations.localeName,
              ),
              _getSectionContent(
                'The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, '
                'or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, '
                'We cannot guarantee its absolute security.',
                'أمان بياناتك الشخصية مهم بالنسبة لنا، لكن تذكر أنه لا توجد طريقة نقل عبر الإنترنت '
                'أو طريقة تخزين إلكتروني آمنة بنسبة 100%. بينما نسعى جاهدين لاستخدام وسائل معقولة تجاريًا لحماية بياناتك الشخصية، '
                'لا يمكننا ضمان أمانها المطلق.',
                localizations.localeName,
              ),
            ),
            const SizedBox(height: 32),
            _buildSection(
              context,
              theme,
              _getSectionTitle(
                'Children\'s Privacy',
                'خصوصية الأطفال',
                localizations.localeName,
              ),
              _getSectionContent(
                'Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information '
                'from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, '
                'please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification '
                'of parental consent, We take steps to remove that information from Our servers.',
                'خدمتنا لا تخاطب أي شخص يقل عمره عن 13 عامًا. لا نجمع معلومات تعريف شخصية عن قصد '
                'من أي شخص يقل عمره عن 13 عامًا. إذا كنت والدًا أو وصيًا وكنت على علم بأن طفلك قد زودنا ببيانات شخصية، '
                'يرجى الاتصال بنا. إذا علمنا أننا جمعنا بيانات شخصية من أي شخص يقل عمره عن 13 عامًا دون التحقق '
                'من موافقة الوالدين، نتخذ خطوات لإزالة تلك المعلومات من خوادمنا.',
                localizations.localeName,
              ),
            ),
            const SizedBox(height: 32),
            _buildSection(
              context,
              theme,
              _getSectionTitle(
                'Links to Other Websites',
                'روابط لمواقع ويب أخرى',
                localizations.localeName,
              ),
              _getSectionContent(
                'Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, '
                'You will be directed to that third party\'s site. We strongly advise You to review the Privacy Policy of every site You visit.\n\n'
                'We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.',
                'قد تحتوي خدمتنا على روابط لمواقع ويب أخرى لا نديرها. إذا نقرت على رابط طرف ثالث، '
                'سيتم توجيهك إلى موقع ذلك الطرف الثالث. ننصحك بشدة بمراجعة سياسة الخصوصية لكل موقع تزوره.\n\n'
                'ليس لدينا أي سيطرة ولا نتحمل أي مسؤولية عن محتوى أو سياسات الخصوصية أو ممارسات أي مواقع أو خدمات لطرف ثالث.',
                localizations.localeName,
              ),
            ),
            const SizedBox(height: 32),
            _buildSection(
              context,
              theme,
              _getSectionTitle(
                'Changes to this Privacy Policy',
                'التغييرات على سياسة الخصوصية هذه',
                localizations.localeName,
              ),
              _getSectionContent(
                'We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.\n\n'
                'We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.\n\n'
                'You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.',
                'قد نحدث سياسة الخصوصية الخاصة بنا من وقت لآخر. سنخطرك بأي تغييرات عن طريق نشر سياسة الخصوصية الجديدة على هذه الصفحة.\n\n'
                'سنخبرك عبر البريد الإلكتروني و/أو إشعار بارز على خدمتنا، قبل أن يصبح التغيير ساري المفعول ونحدث تاريخ "آخر تحديث" في أعلى سياسة الخصوصية هذه.\n\n'
                'ينصح بمراجعة سياسة الخصوصية هذه بشكل دوري لأي تغييرات. التغييرات على سياسة الخصوصية هذه سارية عند نشرها على هذه الصفحة.',
                localizations.localeName,
              ),
            ),
            const SizedBox(height: 32),
            _buildSection(
              context,
              theme,
              _getSectionTitle(
                'Contact Us',
                'اتصل بنا',
                localizations.localeName,
              ),
              _getSectionContent(
                'If you have any questions about this Privacy Policy, You can contact us:\n\n'
                '• By email: raqami2026@outlook.com',
                'إذا كان لديك أي أسئلة حول سياسة الخصوصية هذه، يمكنك الاتصال بنا:\n\n'
                '• عبر البريد الإلكتروني: raqami2026@outlook.com',
                localizations.localeName,
              ),
            ),
            const SizedBox(height: 32),
          ],
        ),
      ),
    );
  }

  Widget _buildSection(
    BuildContext context,
    RaqamiThemeData theme,
    String title,
    String content,
  ) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        RaqamiText(
          title,
          style: RaqamiTextStyles.heading4,
          textColor: theme.colors.foregroundPrimary,
        ),
        const SizedBox(height: 12),
        RaqamiText(
          content,
          style: RaqamiTextStyles.bodyBaseRegular,
          textColor: theme.colors.foregroundSecondary,
        ),
      ],
    );
  }
}
